# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='areas',
        ),
        migrations.AddField(
            model_name='question',
            name='areas',
            field=models.ManyToManyField(default=None, to='app.Preference'),
        ),
    ]
