# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171213_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='keywords',
        ),
        migrations.AddField(
            model_name='reply',
            name='keywords',
            field=models.ManyToManyField(default=None, to='app.Keyword'),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(default=None, to='app.Keyword'),
        ),
    ]
