# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171213_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='areas',
            field=models.ManyToManyField(blank=True, default=None, to='app.Area'),
        ),
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, to='app.Keyword'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='keywords',
            field=models.ManyToManyField(blank=True, default=None, to='app.Keyword'),
        ),
        migrations.AlterField(
            model_name='user',
            name='areas',
            field=models.ManyToManyField(blank=True, default=None, to='app.Area'),
        ),
    ]
